version : "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: benat_container
    ports:
      - '1002:3000'
    volumes:
      - .:/app
      - /app/node_modules